// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: educations.proto

package genprotos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EducationServiceClient is the client API for EducationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EducationServiceClient interface {
	CreateEducation(ctx context.Context, in *Education, opts ...grpc.CallOption) (*Void, error)
	DeleteEducation(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
	UpdateEducation(ctx context.Context, in *Education, opts ...grpc.CallOption) (*Void, error)
	GetByIdEducation(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Education, error)
	GetAllEducation(ctx context.Context, in *Education, opts ...grpc.CallOption) (*GetAllEducations, error)
}

type educationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEducationServiceClient(cc grpc.ClientConnInterface) EducationServiceClient {
	return &educationServiceClient{cc}
}

func (c *educationServiceClient) CreateEducation(ctx context.Context, in *Education, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/protos.EducationService/CreateEducation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) DeleteEducation(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/protos.EducationService/DeleteEducation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) UpdateEducation(ctx context.Context, in *Education, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/protos.EducationService/UpdateEducation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) GetByIdEducation(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Education, error) {
	out := new(Education)
	err := c.cc.Invoke(ctx, "/protos.EducationService/GetByIdEducation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *educationServiceClient) GetAllEducation(ctx context.Context, in *Education, opts ...grpc.CallOption) (*GetAllEducations, error) {
	out := new(GetAllEducations)
	err := c.cc.Invoke(ctx, "/protos.EducationService/GetAllEducation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EducationServiceServer is the server API for EducationService service.
// All implementations must embed UnimplementedEducationServiceServer
// for forward compatibility
type EducationServiceServer interface {
	CreateEducation(context.Context, *Education) (*Void, error)
	DeleteEducation(context.Context, *ById) (*Void, error)
	UpdateEducation(context.Context, *Education) (*Void, error)
	GetByIdEducation(context.Context, *ById) (*Education, error)
	GetAllEducation(context.Context, *Education) (*GetAllEducations, error)
	mustEmbedUnimplementedEducationServiceServer()
}

// UnimplementedEducationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEducationServiceServer struct {
}

func (UnimplementedEducationServiceServer) CreateEducation(context.Context, *Education) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEducation not implemented")
}
func (UnimplementedEducationServiceServer) DeleteEducation(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEducation not implemented")
}
func (UnimplementedEducationServiceServer) UpdateEducation(context.Context, *Education) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEducation not implemented")
}
func (UnimplementedEducationServiceServer) GetByIdEducation(context.Context, *ById) (*Education, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIdEducation not implemented")
}
func (UnimplementedEducationServiceServer) GetAllEducation(context.Context, *Education) (*GetAllEducations, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllEducation not implemented")
}
func (UnimplementedEducationServiceServer) mustEmbedUnimplementedEducationServiceServer() {}

// UnsafeEducationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EducationServiceServer will
// result in compilation errors.
type UnsafeEducationServiceServer interface {
	mustEmbedUnimplementedEducationServiceServer()
}

func RegisterEducationServiceServer(s grpc.ServiceRegistrar, srv EducationServiceServer) {
	s.RegisterService(&EducationService_ServiceDesc, srv)
}

func _EducationService_CreateEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Education)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).CreateEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EducationService/CreateEducation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).CreateEducation(ctx, req.(*Education))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_DeleteEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).DeleteEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EducationService/DeleteEducation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).DeleteEducation(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_UpdateEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Education)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).UpdateEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EducationService/UpdateEducation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).UpdateEducation(ctx, req.(*Education))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_GetByIdEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetByIdEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EducationService/GetByIdEducation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetByIdEducation(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _EducationService_GetAllEducation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Education)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EducationServiceServer).GetAllEducation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EducationService/GetAllEducation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EducationServiceServer).GetAllEducation(ctx, req.(*Education))
	}
	return interceptor(ctx, in, info, handler)
}

// EducationService_ServiceDesc is the grpc.ServiceDesc for EducationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EducationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.EducationService",
	HandlerType: (*EducationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEducation",
			Handler:    _EducationService_CreateEducation_Handler,
		},
		{
			MethodName: "DeleteEducation",
			Handler:    _EducationService_DeleteEducation_Handler,
		},
		{
			MethodName: "UpdateEducation",
			Handler:    _EducationService_UpdateEducation_Handler,
		},
		{
			MethodName: "GetByIdEducation",
			Handler:    _EducationService_GetByIdEducation_Handler,
		},
		{
			MethodName: "GetAllEducation",
			Handler:    _EducationService_GetAllEducation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "educations.proto",
}
